server:
  port: 8080

short-root-path: http://localhost:8080/urls/

spring:
  h2:
    console:
      enabled: true
  datasource:
    initialization-mode: always
    schema:    - classpath:schema.sql

mybatis:
  type-aliases-package: com.kjh.shorturl.entity
  mapper-locations:  - classpath:com/kjh/shorturl/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

  