CREATE TABLE `SHORT_URL` (
	`SHORT_URL_IDX` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`PROTOCOL` VARCHAR(8) NOT NULL,
	`HOST` VARCHAR(50) NOT NULL,
	`PORT` INT(11) NULL DEFAULT NULL,
	`PATHNAME` VARCHAR(100) NULL DEFAULT NULL,
	`SHORTING_URL` VARCHAR(100) ,
	`REQUEST_COUNT` INT(10) UNSIGNED NOT NULL,
	`CREATE_DATE` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`SHORT_URL_IDX`)
);
